### ISSUE TITLE
Code Review for Ruby Capstone Project

### ISSUE THREAD

**Issue by huseyinbiyik** [huseyinbiyik/my-catalog#37]
Hello, here is our project link: https://github.com/huseyinbiyik/my-catalog

On this project, we are a group of 3 people: @huseyinbiyik @ahzamir @bamsi 

Here is the assignment for group members
Team Member#1 : @ahzamir 
Team Member#2 : @bamsi 
Team Member#3: @huseyinbiyik 

Thank you for your feedback in advance! 👨‍💻

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by huseyinbiyik** [comment]
Thank you for the feedback, Shoira.
